// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nytxdkvpgbvndtbvcvxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dHhka3ZwZ2J2bmR0YnZjdnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjk0MDQsImV4cCI6MjA2Mjk0NTQwNH0.TpmAezgRrXiLaXFLVC98wPkY3hpV8y0Ogc_EatasxTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);